# Generated by Django 3.2.6 on 2024-01-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_ipv4', models.CharField(max_length=255)),
                ('destination_ipv4', models.CharField(max_length=255)),
                ('source_ipv6', models.CharField(max_length=255)),
                ('destination_ipv6', models.CharField(max_length=255)),
                ('protocol', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
            ],
        ),
    ]
