# Generated by Django 3.2.6 on 2024-01-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficdata',
            name='destination_ipv4',
            field=models.GenericIPAddressField(protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='trafficdata',
            name='destination_ipv6',
            field=models.GenericIPAddressField(protocol='IPv6'),
        ),
        migrations.AlterField(
            model_name='trafficdata',
            name='source_ipv4',
            field=models.GenericIPAddressField(protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='trafficdata',
            name='source_ipv6',
            field=models.GenericIPAddressField(protocol='IPv6'),
        ),
    ]
