# Generated by Django 3.2.6 on 2024-01-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_data', '0002_auto_20240126_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficdata',
            name='destination_ipv4',
            field=models.GenericIPAddressField(null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='trafficdata',
            name='destination_ipv6',
            field=models.GenericIPAddressField(null=True, protocol='IPv6'),
        ),
        migrations.AlterField(
            model_name='trafficdata',
            name='source_ipv4',
            field=models.GenericIPAddressField(null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='trafficdata',
            name='source_ipv6',
            field=models.GenericIPAddressField(null=True, protocol='IPv6'),
        ),
    ]
