# Generated by Django 3.2.6 on 2024-01-26 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('traffic_data', '0003_auto_20240126_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficdata',
            name='username_T',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Person_IP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('source_ipv4', models.GenericIPAddressField(null=True, protocol='IPv4')),
                ('source_ipv6', models.GenericIPAddressField(null=True, protocol='IPv6')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
