# Generated by Django 3.2.6 on 2024-01-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_data', '0004_auto_20240126_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trafficdata',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='trafficdata',
            name='download_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trafficdata',
            name='upload_bytes',
            field=models.BigIntegerField(default=0),
        ),
    ]
