# Generated by Django 3.2.6 on 2024-01-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_data', '0006_alter_trafficdata_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficdata',
            name='size',
        ),
        migrations.AddField(
            model_name='trafficdata',
            name='sizev4',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trafficdata',
            name='sizev6',
            field=models.BigIntegerField(null=True),
        ),
    ]
