# Generated by Django 3.2.6 on 2024-01-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_data', '0013_auto_20240126_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trafficdata',
            old_name='sizev4',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='trafficdata',
            name='sizev6',
        ),
    ]
